"""fresh postgres migration

Revision ID: 1b4ceb771366
Revises: 
Create Date: 2026-02-25 19:12:51.753150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b4ceb771366'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create household without selected_leader_reward_id (circular dep with leaderboard_reward).
    op.create_table('household',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('invite_code', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_code')
    )

    op.create_table('leaderboard_reward',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leaderboard_reward', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leaderboard_reward_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leaderboard_reward_household_id'), ['household_id'], unique=False)

    # Add household.selected_leader_reward_id now that leaderboard_reward exists.
    with op.batch_alter_table('household', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected_leader_reward_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'leaderboard_reward', ['selected_leader_reward_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_household_selected_leader_reward_id'), ['selected_leader_reward_id'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('role', sa.String(length=40), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('streak_count', sa.Integer(), nullable=True),
    sa.Column('last_streak_date', sa.Date(), nullable=True),
    sa.Column('avatar_filename', sa.String(length=255), nullable=True),
    sa.Column('exam_mode', sa.Boolean(), nullable=True),
    sa.Column('dietary_restrictions', sa.Text(), nullable=True),
    sa.Column('cleaning_preferences', sa.Text(), nullable=True),
    sa.Column('availability_notes', sa.Text(), nullable=True),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=True),
    sa.Column('household_id', sa.Integer(), nullable=True),
    sa.Column('active_household_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['active_household_id'], ['household.id'], ),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_active_household_id'), ['active_household_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_household_id'), ['household_id'], unique=False)

    op.create_table('chore',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to_user_id', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_by_id', sa.Integer(), nullable=True),
    sa.Column('points_awarded', sa.Integer(), nullable=True),
    sa.Column('repeat_type', sa.String(length=20), nullable=False, server_default=sa.text("'none'")),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('was_overdue', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['completed_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chore', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chore_assigned_to_user_id'), ['assigned_to_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chore_completed_by_id'), ['completed_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chore_household_id'), ['household_id'], unique=False)

    op.create_table('expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('paid_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ),
    sa.ForeignKeyConstraint(['paid_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expense_household_id'), ['household_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_paid_by_user_id'), ['paid_by_user_id'], unique=False)

    op.create_table('inventory_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('sub_category', sa.String(length=60), nullable=True),
    sa.Column('location', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('use_count', sa.Integer(), nullable=False, server_default=sa.text('0')),
    sa.Column('expiry_type', sa.String(length=20), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('min_stock', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_item_household_id'), ['household_id'], unique=False)

    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('link_url', sa.String(length=255), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_household_id'), ['household_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_user_id'), ['user_id'], unique=False)

    op.create_table('chore_swap_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=True),
    sa.Column('from_user_id', sa.Integer(), nullable=False),
    sa.Column('to_user_id', sa.Integer(), nullable=False),
    sa.Column('offered_chore_id', sa.Integer(), nullable=False),
    sa.Column('requested_chore_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ),
    sa.ForeignKeyConstraint(['offered_chore_id'], ['chore.id'], ),
    sa.ForeignKeyConstraint(['requested_chore_id'], ['chore.id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chore_swap_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chore_swap_request_from_user_id'), ['from_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chore_swap_request_household_id'), ['household_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chore_swap_request_offered_chore_id'), ['offered_chore_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chore_swap_request_requested_chore_id'), ['requested_chore_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chore_swap_request_to_user_id'), ['to_user_id'], unique=False)

    op.create_table('expense_share',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount_owed', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['expense_id'], ['expense.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expense_share', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expense_share_expense_id'), ['expense_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_share_user_id'), ['user_id'], unique=False)

    op.create_table('shopping_list_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('picked_up', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    sa.Column('inventory_item_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shopping_list_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shopping_list_item_household_id'), ['household_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shopping_list_item_inventory_item_id'), ['inventory_item_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('household', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_household_selected_leader_reward_id'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('selected_leader_reward_id')

    with op.batch_alter_table('shopping_list_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shopping_list_item_inventory_item_id'))
        batch_op.drop_index(batch_op.f('ix_shopping_list_item_household_id'))

    op.drop_table('shopping_list_item')
    with op.batch_alter_table('expense_share', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expense_share_user_id'))
        batch_op.drop_index(batch_op.f('ix_expense_share_expense_id'))

    op.drop_table('expense_share')
    with op.batch_alter_table('chore_swap_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chore_swap_request_to_user_id'))
        batch_op.drop_index(batch_op.f('ix_chore_swap_request_requested_chore_id'))
        batch_op.drop_index(batch_op.f('ix_chore_swap_request_offered_chore_id'))
        batch_op.drop_index(batch_op.f('ix_chore_swap_request_household_id'))
        batch_op.drop_index(batch_op.f('ix_chore_swap_request_from_user_id'))

    op.drop_table('chore_swap_request')
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_household_id'))

    op.drop_table('notification')
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_item_household_id'))

    op.drop_table('inventory_item')
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expense_paid_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_expense_household_id'))

    op.drop_table('expense')
    with op.batch_alter_table('chore', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chore_household_id'))
        batch_op.drop_index(batch_op.f('ix_chore_completed_by_id'))
        batch_op.drop_index(batch_op.f('ix_chore_assigned_to_user_id'))

    op.drop_table('chore')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_household_id'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_index(batch_op.f('ix_user_active_household_id'))

    op.drop_table('user')
    with op.batch_alter_table('leaderboard_reward', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leaderboard_reward_household_id'))
        batch_op.drop_index(batch_op.f('ix_leaderboard_reward_created_by_user_id'))

    op.drop_table('leaderboard_reward')
    op.drop_table('household')
    # ### end Alembic commands ###
