"""add chore swap requests

Revision ID: 992af69e95a9
Revises: cc68213093e8
Create Date: 2026-01-29 16:37:01.517132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '992af69e95a9'
down_revision = 'cc68213093e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chore_swap_request', schema=None) as batch_op:
        batch_op.alter_column('requested_chore_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_chore_swap_request_status'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chore_swap_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chore_swap_request_status'), ['status'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('requested_chore_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
