"""add chore swap requests

Revision ID: cc68213093e8
Revises: 114f527dde82
Create Date: 2026-01-29 16:32:06.345209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc68213093e8'
down_revision = '114f527dde82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chore_swap_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=False),
    sa.Column('to_user_id', sa.Integer(), nullable=False),
    sa.Column('offered_chore_id', sa.Integer(), nullable=False),
    sa.Column('requested_chore_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ),
    sa.ForeignKeyConstraint(['offered_chore_id'], ['chore.id'], ),
    sa.ForeignKeyConstraint(['requested_chore_id'], ['chore.id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chore_swap_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chore_swap_request_from_user_id'), ['from_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chore_swap_request_household_id'), ['household_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chore_swap_request_offered_chore_id'), ['offered_chore_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chore_swap_request_requested_chore_id'), ['requested_chore_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chore_swap_request_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_chore_swap_request_to_user_id'), ['to_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chore_swap_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chore_swap_request_to_user_id'))
        batch_op.drop_index(batch_op.f('ix_chore_swap_request_status'))
        batch_op.drop_index(batch_op.f('ix_chore_swap_request_requested_chore_id'))
        batch_op.drop_index(batch_op.f('ix_chore_swap_request_offered_chore_id'))
        batch_op.drop_index(batch_op.f('ix_chore_swap_request_household_id'))
        batch_op.drop_index(batch_op.f('ix_chore_swap_request_from_user_id'))

    op.drop_table('chore_swap_request')
    # ### end Alembic commands ###
